version = "3.11.1"
runner.dialect = scala3
align.preset = more    // 对齐预设：more（更激进的对齐）
align.multiline = false  // 多行表达式是否对齐
maxColumn = 200  // 每行最大列数
continuationIndent.defnSite = 2  // 定义处（如方法参数）续行的缩进空格数
assumeStandardLibraryStripMargin = true  // 假设标准库的 stripMargin 方法可用
docstrings.style = Asterisk  // 文档注释样式：星号(*)风格
docstrings.wrapMaxColumn = 100  // 文档注释换行的最大列数
lineEndings = preserve  // 换行符类型：保持原有格式
includeCurlyBraceInSelectChains = false  // 在选择链中是否包含花括号
danglingParentheses.preset = true  // 悬空括号预设：启用
optIn.annotationNewlines = true  // 注解换行优化：启用
newlines.alwaysBeforeMultilineDef = false  // 多行定义前是否总是添加换行
rewrite.rules = [RedundantBraces]  // 重写规则：移除冗余的花括号
indent.ctorSite = 2 // 控制主构造函数的缩进（case class 的参数列表）
binPack.parentConstructors = Always // 控制 derives 后的特质在同一行
rewrite.redundantBraces.defnBodies = none // 不移除 def 体的花括号